---
run-go:
  stage: build
  script:
    - npm install
    - npm run build

copy-files:
  tags:
    - boop
  stage: deploy
  script:
    - pushd /srv/boop
    - find . -delete
    - popd
    - cp -r . /srv/boop
