deploy-proxmox-abed:
  tags:
    - ichi
  stage: deploy
  script:
    - pushd /srv/boop
    - find . -delete
    - popd
    - cp -r . /srv/boop
    - echo 'API_BASE_URL=${API_BASE_URL}' | envsubst >> /srv/boop/.env
    - sudo /usr/bin/systemctl restart boop

deploy-proxmox-raed:
  tags:
    - ni
  stage: deploy
  script:
    - pushd /srv/boop
    - find . -delete
    - popd
    - cp -r . /srv/boop
    - sudo /usr/bin/systemctl restart boop

deploy-proxmox-elena:
  tags:
    - san
  stage: deploy
  script:
    - pushd /srv/boop
    - find . -delete
    - popd
    - cp -r . /srv/boop
    - sudo /usr/bin/systemctl restart boop
